# Generated by Django 4.2.14 on 2024-07-16 07:41

import wagtail.search.index

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Topics",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
