# Generated by Django 4.2.14 on 2024-07-25 15:01

import django.db.models.deletion
import modelcluster.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("taxonomy", "0002_alter_topic_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTopicRelationship",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="wagtailcore.page"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="related_pages", to="taxonomy.topic"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
