# Generated by Django 4.2.14 on 2024-07-15 15:45

import wagtail.models
import wagtail.search.index

from django.db import migrations, models

import ons_alpha.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_contactdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("chart", ons_alpha.utils.fields.StreamField()),
            ],
            bases=(wagtail.search.index.Indexed, wagtail.models.PreviewableMixin, models.Model),
        ),
    ]
