# Generated by Django 4.2.16 on 2024-09-16 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_chart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chart",
        ),
    ]
