# Generated by Django 4.2.14 on 2024-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasepage",
            name="status",
            field=models.CharField(default="PROVISIONAL", max_length=32),
        ),
    ]
