# Generated by Django 4.2.14 on 2024-08-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release_calendar", "0002_releasepage_datasets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasepage",
            name="status",
            field=models.CharField(default="provisional", max_length=32),
        ),
    ]
