default_language_version:
  node: system
  python: python3.12

repos:
  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.4.10' # keep version in sync with pyproject.toml
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.1' # keep version in sync with version installed in the Dockerfile
    hooks:
      - id: poetry-check
      - id: poetry-lock
        # Never update dependencies and only run on changes to pyproject.toml
        args: [--no-update]
        files: ^pyproject.toml$

  # Template linting
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml

  # Misc. other linters
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0 # keep version in sync with pyproject.toml
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: >
          (?x)^(
              .*/tests/.*|
              package-lock.json|
              poetry.lock
          )$
