# Generated by Django 4.2.14 on 2024-09-04 15:33

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bundles", "0003_remove_bundle_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bundle",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_bundles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
