# Generated by Django 4.2.16 on 2024-10-18 10:49

from django.db import migrations, models

import ons_alpha.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="call_to_action",
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=ons_alpha.utils.fields.StreamField(block_lookup={}, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
