# Generated by Django 4.2.11 on 2024-07-01 10:50

import wagtail.fields

from django.db import migrations

import ons_alpha.core.blocks.markup


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletinpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", ons_alpha.core.blocks.markup.HeadingBlock())],
                default={},
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
