# Generated by Django 4.2.11 on 2024-07-04 15:02

import django.db.models.deletion

from django.db import migrations, models

import ons_alpha.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_contactdetails"),
        ("bulletins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletinpage",
            name="contact_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.contactdetails",
            ),
        ),
        migrations.AddField(
            model_name="bulletinpage",
            name="is_accredited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulletinpage",
            name="updates",
            field=ons_alpha.utils.fields.StreamField(blank=True, use_json_field=True),
        ),
    ]
