# Generated by Django 4.2.14 on 2024-07-12 11:42

import django.db.models.deletion
import wagtail.contrib.routable_page.models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("bulletins", "0002_bulletinpage_contact_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinSeriesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page"),
        ),
    ]
