# Generated by Django 4.2.14 on 2024-07-16 07:41

import django.db.models.deletion
import modelcluster.fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
        ("bulletins", "0002_bulletinpage_contact_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinTopicRelationship",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="bulletins.bulletinpage"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bulletins", to="taxonomy.topic"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
