# Generated by Django 4.2.11 on 2024-07-01 12:16

from django.db import migrations

import ons_alpha.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0002_bulletinpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletinpage",
            name="body",
            field=ons_alpha.utils.fields.StreamField(use_json_field=True),
        ),
    ]
