# Generated by Django 4.2.11 on 2024-07-01 14:04

import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0003_alter_bulletinpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletinpage",
            name="next_release_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bulletinpage",
            name="release_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
