# Generated by Django 4.2.14 on 2024-07-17 16:00

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release_calendar", "0001_initial"),
        ("bulletins", "0004_bulletintopicrelationship"),
        ("release_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletinpage",
            name="release_calendar_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_bulletins",
                to="release_calendar.releasepage",
            ),
        ),
    ]
