# Generated by Django 4.2.16 on 2024-10-02 16:49

from django.db import migrations

import ons_alpha.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bulletins", "0006_bulletinpage_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletinpage",
            name="headline_figures",
            field=ons_alpha.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
    ]
