# Generated by Django 3.2.12 on 2022-05-31 10:42

from django.db import migrations

import ons_alpha.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personpage",
            name="biography",
            field=ons_alpha.utils.fields.StreamField(
                blank=True, use_json_field=True
            ),
        ),
    ]
