# Generated by Django 4.2.16 on 2024-10-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barchart",
            name="show_value_labels",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="linechart",
            name="show_value_labels",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="barchart",
            name="x_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="barchart",
            name="y_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="x_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="y_label",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
