# Generated by Django 4.2.16 on 2024-10-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0003_barchart_x_type_linechart_x_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barchart",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="barchart",
            name="title",
        ),
        migrations.RemoveField(
            model_name="linechart",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="linechart",
            name="title",
        ),
        migrations.AddField(
            model_name="chart",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chart",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
