# Generated by Django 4.2.16 on 2024-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0004_remove_barchart_subtitle_remove_barchart_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barchart",
            name="theme",
            field=models.CharField(default="primary", max_length=10),
        ),
        migrations.AddField(
            model_name="linechart",
            name="theme",
            field=models.CharField(default="primary", max_length=10),
        ),
    ]
