# Generated by Django 4.2.16 on 2024-11-01 15:52

import wagtail.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0005_barchart_theme_linechart_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="caption",
            field=wagtail.fields.RichTextField(blank=True, default="Source: Office for National Statistics"),
        ),
    ]
