# Generated by Django 4.2.16 on 2024-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0006_chart_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="barchart",
            name="height",
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name="linechart",
            name="height",
            field=models.IntegerField(default=400),
        ),
    ]
