# Generated by Django 4.2.16 on 2024-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0007_barchart_height_linechart_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="barchart",
            name="x_tick_interval",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="barchart",
            name="y_tick_interval",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="linechart",
            name="x_tick_interval",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="linechart",
            name="y_tick_interval",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
