# Generated by Django 4.2.16 on 2024-11-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0008_barchart_x_tick_interval_barchart_y_tick_interval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chart",
            name="acls_last_set",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="last_private_collection",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="last_public_collection",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="privacy_last_changed",
        ),
    ]
