# Generated by Django 4.2.16 on 2024-11-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0009_remove_chart_acls_last_set_remove_chart_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barchart",
            name="x_tick_interval",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="barchart",
            name="y_tick_interval",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="x_tick_interval",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="y_tick_interval",
            field=models.FloatField(default=0),
        ),
    ]
