# Generated by Django 4.2.16 on 2024-11-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0010_alter_barchart_x_tick_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barchart",
            name="x_tick_interval",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="barchart",
            name="y_tick_interval",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="x_tick_interval",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="y_tick_interval",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
