# Generated by Django 4.2.16 on 2024-11-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0012_alter_barchart_data_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
    ]
