# Generated by Django 4.2.16 on 2024-11-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0013_chart_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="barchart",
            name="data_headers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="linechart",
            name="data_headers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
