# Generated by Django 4.2.14 on 2024-07-16 07:41

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="topic",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="topic_page", to="taxonomy.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicsectionpage",
            name="topic",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topic_section_page",
                to="taxonomy.topic",
            ),
        ),
    ]
