# Generated by Django 4.2.14 on 2024-07-16 17:34

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_alter_topic_name"),
        ("topics", "0002_topicpage_topic_topicsectionpage_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicpage",
            name="topic",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s", to="taxonomy.topic"
            ),
        ),
        migrations.AlterField(
            model_name="topicsectionpage",
            name="topic",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s", to="taxonomy.topic"
            ),
        ),
    ]
