# Generated by Django 4.2.14 on 2024-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_alter_topicpage_topic_alter_topicsectionpage_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topicsectionpage",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
