# Generated by Django 4.2.16 on 2024-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0004_alter_topicpage_topic_alter_topicsectionpage_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topicsectionpage",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
