# Generated by Django 4.2.14 on 2024-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_alter_topicpage_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="topic_page_nav",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
