# Generated by Django 4.2.16 on 2024-10-03 05:42

from django.db import migrations

import ons_alpha.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_topicpage_summary_topicsectionpage_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="body",
            field=ons_alpha.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.AddField(
            model_name="topicpage",
            name="headline_figures",
            field=ons_alpha.utils.fields.StreamField(blank=True, block_lookup={}),
        ),
    ]
