# Generated by Django 4.2.14 on 2024-08-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0006_topicpage_topic_page_nav"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicpage",
            name="topic_page_nav",
        ),
    ]
