# Generated by Django 4.2.14 on 2024-08-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0007_remove_topicpage_topic_page_nav"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="topic_page_nav",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
