# Generated by Django 4.2.16 on 2024-09-12 13:29

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectedCollection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    "collection",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="wagtailcore.collection"),
                ),
            ],
        ),
    ]
