# Generated by Django 4.2.16 on 2024-09-13 09:43

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdocument",
            name="acls_last_set",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customdocument",
            name="is_private",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="customdocument",
            name="last_private_collection",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.collection",
            ),
        ),
        migrations.AddField(
            model_name="customdocument",
            name="last_public_collection",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.collection",
            ),
        ),
        migrations.AddField(
            model_name="customdocument",
            name="privacy_last_changed",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
