# Generated by Django 4.2.16 on 2024-10-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="informationpage",
            old_name="introduction",
            new_name="summary",
        ),
        migrations.AddField(
            model_name="informationpage",
            name="strapline",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
