# Generated by Django 4.2.14 on 2024-07-25 15:20

import django.db.models.deletion

from django.db import migrations, models

import ons_alpha.bundles.models
import ons_alpha.utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0093_uploadedfile"),
        ("core", "0003_chart"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodologyPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("listing_title", models.CharField(blank=True, max_length=255)),
                ("listing_summary", models.CharField(blank=True, max_length=255)),
                ("social_text", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField()),
                ("last_revised_date", models.DateField(blank=True, null=True)),
                ("how_it_was_revised", models.CharField(blank=True, max_length=255)),
                ("geographic_coverage", models.CharField(blank=True, max_length=255)),
                ("is_accredited", models.BooleanField(default=False)),
                ("body", ons_alpha.utils.fields.StreamField()),
                (
                    "contact_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.contactdetails",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(ons_alpha.bundles.models.BundledPageMixin, "wagtailcore.page", models.Model),
        ),
    ]
